[[functions]]
name = "calculate"
description = "Perform mathematical calculations"
command = "echo '{{expression}}' | bc"
safe = true

[[functions.parameters]]
name = "expression"
type = "string"
description = "Mathematical expression to evaluate"
required = true
