[[functions]]
name = "delete_alarm"
description = "Delete an alarm already based on time"
command = "script '{{time}}'"

[[functions.parameters]]
name = "time"
type = "string"
description = "Time of the alarm to be deleted (HH:mm)"
required = true