[[functions]]
name = "set_alarm"
description = "Set an alarm on the system"
command = ",apple-alarm '{{time}}'"

[[functions.parameters]]
name = "time"
type = "string"
description = "Time to set the alarm (HH:mm)"
required = true

[[functions]]
name = "get_datetime"
description = "Get current date and time"
command = "date"
safe = true

[[functions]]
name = "delete_alarm"
description = "Delete an alarm already based on time"
command = ",alarm-delete '{{time}}'"
safe = false

[[functions.parameters]]
name = "time"
type = "string"
description = "Time of the alarm to be deleted (HH:mm)"
required = true

[[functions]]
name = "open_website"
description = "Open a website in the default browser"
command = "open '{{url}}'"
safe = true

[[functions.parameters]]
name = "url"
type = "string"
description = "URL of the website to open"
required = true

[[functions]]
name = "adjust_brightness"
description = "Adjust screen brightness"
command = ",adjust-brightness '{{level}}'"

[[functions.parameters]]
name = "level"
type = "string"
description = "Direction to adjust brightness (increase/decrease)"
required = true

[[functions]]
name = "get_weather"
description = "Get current weather information"
command = "script"
safe = true

[[functions]]
name = "volume_control"
description = "Adjust system volume"
command = "script '{{direction}}'"

[[functions.parameters]]
name = "direction"
type = "string"
description = "Direction to adjust volume (increase/decrease/mute)"
required = true

[[functions]]
name = "send_email"
description = "Send an email"
command = "script '{{recipient}}' '{{subject}}' '{{body}}'"
safe = false

[[functions.parameters]]
name = "recipient"
type = "string"
description = "Recipient email address"
required = true

[[functions.parameters]]
name = "subject"
type = "string"
description = "Email subject"
required = true

[[functions.parameters]]
name = "body"
type = "string"
description = "Email body"
required = true
