[[functions]]
name = "volume_control"
description = "Adjust system volume"
command = "script '{{direction}}'"
safe = true

[[functions.parameters]]
name = "direction"
type = "string"
description = "Direction to adjust volume (increase/decrease/mute)"
required = true
