#!/usr/bin/osascript

on run argv
    set volumeDirection to item 1 of argv

    tell application "System Events"
        if volumeDirection is "increase" then
            key code 144 -- Volume up
        else if volumeDirection is "decrease" then
            key code 145 -- Volume down
        else if volumeDirection is "mute" then
            key code 146 -- Mute
        end if
    end tell
    return "Volume " & volumeDirection & "d"
end run
