[[functions]]
name = "search_files"
description = "Search for files matching a pattern"
command = "find . -name '{{pattern}}'"

[[functions.parameters]]
name = "pattern"
type = "string"
description = "File name pattern to search for"
required = true
