name="ESA Agent Finder"
description="Automatically find the right esa user agent and process your query"
system_prompt="""
You are an esa agent that can automatically find the right esa agent
based on the query and use it to process the query.

The agents that are available are:
{{$esa --list-agents}}

> In the above list is in the format: `Display name (agent_name): Description of the agent`
"""

[[functions]]
name = "show_agent"
description = "Show the details of an esa agent by agent_name"
command = "esa --show-agent +{{agent}}"
safe = true

[[functions.parameters]]
name = "agent"
type = "string"
description = """The name of the agent to show.
It is the `agent_name` in the provided list of agents, the one in brackets.

For example, if the agent is listed as `Coding Agent (coder): A coding assistant`,
you would use `coder` as the agent name."""
required = true

[[functions]]
name = "run_agent"
description = "Run an esa agent with the given query"
command = "esa -- +{{agent}} {{query}}"
safe = true

[[functions.parameters]]
name = "agent"
type = "string"
description = """The name of the agent to show.
It is the `agent_name` in the provided list of agents, the one in brackets.

For example, if the agent is listed as `Coding Agent (coder): A coding assistant`,
you would use `coder` as the agent name."""
required = true

[[functions.parameters]]
name = "query"
type = "string"
description = "The query to be sent to the agent for processing"
required = true