[[functions]]
name = "run_python_interpreter"
description = "Run a python command"
command = "python -c '{{command}}'"

[[functions.parameters]]
name = "command"
type = "string"
description = "Python command to execute"
required = true
