[[functions]]
name = "write_file"
description = "Write content to a file"
command = "script '{{filename}}' '{{content}}'"

[[functions.parameters]]
name = "filename"
type = "string"
description = "Name of the file to write to"
required = true

[[functions.parameters]]
name = "content"
type = "string"
description = "Content to write to the file"
required = true
