[[functions]]
name = "send_email"
description = "Send an email"
command = "script '{{recipient}}' '{{subject}}' '{{body}}'"

[[functions.parameters]]
name = "recipient"
type = "string"
description = "Recipient email address"
required = true

[[functions.parameters]]
name = "subject"
type = "string"
description = "Email subject"
required = true

[[functions.parameters]]
name = "body"
type = "string"
description = "Email body"
required = true
