[[functions]]
name = "send_notification"
description = "Send a system notification"
command = "notify-send '{{title}}' '{{message}}'"

[[functions.parameters]]
name = "title"
type = "string"
description = "Title of the notification"
required = true

[[functions.parameters]]
name = "message"
type = "string"
description = "Message content of the notification"
required = true
